### ISSUE TITLE
How convert XTF to Geotiff?

### ISSUE THREAD

**Issue by CarvalhoResearch** [oysstu/pyxtf#11]

**Comment by oysstu** [comment]
With measurements of altitude and attitude (roll, pitch, yaw), combined with either the slant range/ground range or sound speed + time of flight of the ping, you can compute the horizontal position for each point of measurement in each ping.

This is unfortunately out of scope for this library, which focuses on XTF input/output. I suggest you look at something like [OpenSidescan](https://github.com/CIDCO-dev/OpenSidescan), to see if they have some routines that can be helpful if you are unable to implement this yourself.

Edit: without knowledge of the bathymetry in the area, the above assumes a flat seabed

**Comment by CarvalhoResearch** [comment]
thank you very much
