### ISSUE TITLE
Run plot_sonar_paythy.py in examples

### ISSUE THREAD

**Issue by wlc-git** [oysstu/pyxtf#13]
Why do I keep getting errors calling the Qt platform when I run plot_sonar_paythy.py in examples, "The following (supported) packets are present (XTFHeaderType:count): ['sonar:10']
"And" qt.qpa.plugin: Could not load the Qt platform plugin "XCB"

**Comment by oysstu** [comment]
This usually indicates that matplotlib is unable to initialize the selected backend. Either resolve the issue with the Qt backend or select another backend
