### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by RobM-RMU** [oysstu/pyxtf#32]
pyxtf is a great module and I appreciate the developer putting it up. I use it to extract track from XTFs. Recently I am getting memory errors with exceptionally large SSS-only XTFs (30 km plus, 50 m range). I think the maximum array size is being exceeded. Computer memory is wide open (55 GB of 64 GB still available). Is there any way, at this initial stage:

```
input_file = 'yourfile.xtf'
(file_header, packets) = pyxtf.xtf_read(input_file, verbose=True)
```

to decimate the input so as to only read in, say, every second trace or ping? Failure point is the second line above, so inside the pyxtf module. Thanks for your advice.

**Comment by oysstu** [comment]
Hi, try to use the xtf_read_gen function instead. The first returned object is the file header and then the packets follow, possibly filtered by type. This incrementally reads the file, see xtf_read for how this is used.

https://github.com/oysstu/pyxtf/blob/a89dc9d5f75df4ef29271784abb4e55a28c6d476/pyxtf/xtf_io.py#L42

**Comment by RobM-RMU** [comment]
Thank you for the fast response. I see that and will try it out, and report back.

**Comment by oysstu** [comment]
Closing, as I assume this has been resolved. Feel free to comment or reopen if that is not the case.
