### ISSUE TITLE
pyxtf error

### ISSUE THREAD

**Issue by robbyrob11** [oysstu/pyxtf#4]
in xtf_ctypes.py

in the for loop from line 562 to 591, all instances of file_header.sonar_info[i] should instead be file_header.sonar_info[i-1]

the index is off by 1

**Comment by oysstu** [comment]
In that case, the first iteration will have a negative index, i.e. wrap around sonar_info. Do you have an example file where this problem occurs? It may be the presence of bathy/subbottom channels that causes the wrong index.

- Øystein

**Comment by oysstu** [comment]
I went through the code, and didn't find anything that immediately looked wrong. I did however find some other bugs. Please open a new issue if you still have the problem, and supply some more information or data
