### ISSUE TITLE
XTF-problems-report

### ISSUE THREAD

**Issue by asaddececxs** [oysstu/pyxtf#49]
I don't know how to solve the following error when running my own MBES XTF file with a script again?

![屏幕截图 2024-12-10 123712](https://github.com/user-attachments/assets/aec898ac-85f8-40f7-8f22-a8d7228a3951)

**Comment by asaddececxs** [comment]
The problematic data is here.
https://github.com/asaddececxs/XTF_Data.git

**Comment by oysstu** [comment]
These packets are returned as raw bytes because they are not described by the XTF specification. You will have to find them in the vendor documentation and either parse them yourself from the data field, or implement a ctypes-structure for those packets.

**Comment by asaddececxs** [comment]
Thanks,sir!



---Original---
From: "Øystein ***@***.***&gt;
Date: Tue, Dec 10, 2024 15:53 PM
To: ***@***.***&gt;;
Cc: "Sphia &amp;&amp; ***@***.******@***.***&gt;;
Subject: Re: [oysstu/pyxtf] XTF-problems-report (Issue #49)




 
These packets are returned as raw bytes because they are not described by the XTF specification. You will have to find them in the vendor documentation and either parse them yourself from the data field, or implement a ctypes-structure for those packets.

**Comment by oysstu** [comment]
No problem. There are some data structures listed in the appendix of the XTF X41 specification, perhaps they can help. I have not worked with reson XTF data before, so I cannot comment on how up to date they are. 

I will close this issue, but feel free to leave a comment if you figure something out. Perhaps it is of interest to others.
