### ISSUE TITLE
Convert .xxx to xtf files

### ISSUE THREAD

**Issue by HikariS97** [oysstu/pyxtf#8]
Hi

I recently start working on SSS, and got several SSS data in different formats, such as .875, .jsf. I'm wondering if there's an open-source or free software available for converting different formats to a unified XTF format. I'm considering to develop such a module to remove barriers in the way of sss data processing...

**Comment by oysstu** [comment]
I believe there's some attempts at common file formats for multibeam echosounders, but nothing that encompasses every aspect of XTF files as far as I know (e.g. MBARI MB-System, Hydroffice). XTF has been adopted by different vendors as the most portable and open format, and each vendor typically either supports direct output to XTF or a conversion utility from their own proprietary format to XTF. I suppose this is why nothing like this exists already.

If I were to do this, I would probably implement each format stand-alone (e.g. pyjsf, py875), and use pyxtf as a dependency to write to xtf.

**Comment by HikariS97** [comment]
Thank you.

**Comment by arlottandrea** [comment]
hey @HikariS97 did you succeed to create a converter script?

**Comment by HikariS97** [comment]
> hey [@HikariS97](https://github.com/HikariS97) did you succeed to create a converter script?

Hi Arlottandrea, it's a long time ago, I actually even forget the project I was working on. In my impression, I ultimately chose to read the SSS or MBES data myself because both have very detailed documentation. Perhaps now you just need to let an AI like GPT handle trivial tasks like bits, and maybe you can easily get a Python or Matlab structure containing all the information.
