### ISSUE TITLE
File indexing

### ISSUE THREAD

**Issue by mlincett** [oysstu/pyxtf#9]
In the current implementation an index file is produced at the first reading of the XTF and is subsequently loaded in a way that is transparent to the user.

In general, I would not expect a "read" method to "write" something, and I would not expect a method to silently work differently between the first and the second call. (Also I find a bit dangerous to do file I/O inside a generator).

Maybe it could be better to decouple the generation/loading of the index file and leave some control to the user?

**Comment by oysstu** [comment]
Yes, it could be a parameter in the read function, which defaults to false. Shouldn't be too hard to implement.

**Comment by mlincett** [comment]
Good! I will attempt some restructuring as soon as I am done with my current project as a user (thanks for developing this!)

**Comment by oysstu** [comment]
Finally got around to doing this. Resolved in https://github.com/oysstu/pyxtf/commit/861a5f52ec30ab8fd83c988aa275d97f9d7958aa
